import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import { ProductsProvider } from "@/context/ProductsContext";
import { ParamsProvider } from "@/context/ParamsContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProductsProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ParamsProvider>
            <div className="min-h-screen bg-black text-white">
              {/* Header */}
              <Header />
              {children}
            </div>
          </ParamsProvider>
        </body>
      </ProductsProvider>
    </html>
  );
}
